apiVersion: kagent.dev/v1alpha1
kind: Agent
metadata:
  name: kyverno-agent
  namespace: kagent
spec:
  description: Kyverno Policy Assistant with MCP integration
  modelConfig: default-model-config
  systemMessage: |
    You are a Kubernetes security assistant using Kyverno to generate and evaluate policies.
    Always use MCP tools for accurate cluster data.

    Example queries you support:
    - Scan my cluster for policy violations
    - Show me RBAC issues in the cluster
    - List available Kubernetes contexts
  tools:
    - type: McpServer
      mcpServer:
        toolServer: kyverno-toolserver
        toolNames:
          - list_contexts
          - switch_context
          - show_violations
          - apply_policies
          - help